services:
  - type: web
    name: ai-air-quality-prediction-platform
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        value: AQ.Ab8RN6LJemX47w9cct6N9bKqR4d3twth_nHiE0yX-noU0oYuLA
